// action - customization reducer
export const SET_MENU = "@customization/SET_MENU"
export const MENU_TOGGLE = "@customization/MENU_TOGGLE"
export const MENU_OPEN = "@customization/MENU_OPEN"
export const SET_FONT_FAMILY = "@customization/SET_FONT_FAMILY"
export const SET_BORDER_RADIUS = "@customization/SET_BORDER_RADIUS"

// Notification
export const SET_DEVICE_NOTIFICATION = "SET_DEVICE_NOTIFICATION"
export const ADD_DEVICE_NOTIFICATION = "ADD_DEVICE_NOTIFICATION"

export const SET_MESSAGE_NOTIFICATION = "SET_MESSAGE_NOTIFICATION"
export const SET_UNREAD_CONVERSATION = "SET_UNREAD_CONVERSATION"
export const PUSH_TO_UNREAD_CONVERSATION = "PUSH_TO_UNREAD_CONVERSATION"
export const PULL_FROM_UNREAD_CONVERSATION = "PULL_FROM_UNREAD_CONVERSATION"

// Admin
export const SET_FETCHED_USERS_DATA = "SET_FETCHED_USERS_DATA"
export const PUSH_FETCHED_USERS_DATA = "PUSH_FETCHED_USERS_DATA"
export const PULL_FETCHED_USERS_DATA = "PULL_FETCHED_USERS_DATA"
export const UPDATE_FETCHED_USERS_DATA = "UPDATE_FETCHED_USERS_DATA"
export const SET_USER_FEEDBACK = "SET_USER_FEEDBACK"


// Scheme
export const SET_FETCHED_DATA = "SET_FETCHED_DATA"
export const PUSH_FETCHED_DATA = "PUSH_FETCHED_USERS_DATA"
export const PULL_FETCHED_DATA = "PULL_FETCHED_USERS_DATA"
export const UPDATE_FETCHED_DATA = "UPDATE_FETCHED_USERS_DATA"
export const SET_FEEDBACK = "SET_USER_FEEDBACK"

